#!/usr/bin/env bash
# Installing nginx webserver on the remote server

# make sure that the systme is updated
sudo apt-get -y update

# install nginx using the -y --yes option
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

# let configure the html file so that we can be able to return the phrase 'Hello World!'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debain.html

# reloading the nginx with the reload option passed
sudo service nginx restart
