#!/usr/bin/env bash
# Installing nginx webserver on the remote server

# make sure that the systme is updated
apt-get update

# install nginx using the -y --yes option
apt-get -y install nginx

# let configure the html file so that we can be able to return the phrase 'Hello World!'
chmod 777 /var/www/html/index.html

echo "Hello World!" > /var/www/html/index.html

chmod 644 /var/www/html/index.html

# reloading the nginx with the reload option passed
/etc/init.d/nginx restart
