#!/usr/bin/env bash
# redirection
target="# pass PHP scripts to FastCGI server"
append="location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

apt update
apt install nginx -y
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sed -i "s%$target%$append%g" /etc/nginx/sites-enabled/default
service nginx restart
