#!/usr/bin/env bash
# adding a redirection url
apt-get update
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
sed -i '/# pass PHP script to FastCGI server/ a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\n\t}' /etc/nginx/sites-available/default
service nginx restart
