#!/usr/bin/env bash
# Adding custom headers to a server

hostName=$(hostname)
id=307078

# checking if hostname is correct
if [[ ! "$hostName" =~ ^$id-web-[0-9]+ ]];
then
	(>&2 echo "Failed: Bad hostname")
	(>&2 echo "Run: hostnamectl set-hostname $id-web-<server_id>")
fi

#---------------------------#
#    Server NGINX Setup
#---------------------------#
sudo apt-get update -y
sudo apt-get install nginx -y

echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

printf %s "server {

    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;
    server_name _;
    # added a custom header
    add_header X-Served-By $hostName;

    location / {
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
        location = /404.html {
        root /var/www/html;
                internal;
        }

}" | sudo tee /etc/nginx/sites-enabled/default

# still not running yet fire up nginx with the new configs
sudo service nginx start

# alereay running you will need a restart to reload all the new configuration
sudo service nginx restart
