#!/usr/bin/env bash
# c format of handling signals
handler() {
	# generate a file containing the pid of this file
	if [[ $1 == "SIGTERM" ]]; then
		rm /var/run/myscript.pid
		echo "I hate the kill command"
	elif [[ $1 == "SIGINT" ]]; then
		echo "Y U no love me?!"
	elif [[ $1 == "SIGQUIT" ]]; then
		rm /var/run/myscript.pid
	fi
	exit 0
}
pgrep -fo "100-process_and_pid_file" > /var/run/myscript.pid
trap 'handler "SIGTERM"' TERM
trap 'handler "SIGINT"' SIGINT
trap 'handler "SIGQUIT"' SIGQUIT

until false; do
	echo "To infinity and beyond"
	sleep 2
done
