#!/usr/bin/env bash
# fixing the new user to run nginx
sudo chmod 6400 /etc/nginx/nginx.conf

# configure nginx.conf to support nginx as the user in control
sudo sed '/user www-data/ c\user nginx' 

# configuring sites-enabled/defaults to allow connection from port 8080
sudo sed  -i 's/80/8080;'

# kill all apache servies listening on port 8080
sudo kill "$(pgrep 'apache' | head -1)"

# restart nginx
sudo -u nginx systemctl restart nginx
