#!/usr/bin/env bash
# fixing the new user to run nginx

# configure nginx.conf to support nginx as the user in control
sudo sed '/user www-data/ c\user nginx' /etc/nginx/nginx.conf

# configuring sites-enabled/defaults to allow connection from port 8080
sudo sed  -i 's/80/8080/' /etc/nginx/sites-enabled/default

# configure nginx.conf to support nginx as the user in control
chown nginx /etc/nginx/nginx.conf

sudo -u nginx chmod 6400 /etc/nginx/nginx.conf

# kill all apache servies listening on port 8080
service apache2 stop
pkill apache2

# restart nginx
sudo -u nginx service nginx restart
