#!/usr/bin/env bash
# applying it all together by allowing nginx to be runned by an nginx user
sudo chmod 644 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
pkill -f apache2
sudo -u nginx service nginx restart
